server:
  port: 33003
spring:
  application:
    name: movie-consumer-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:35001/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
